config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/about', to: 'static_pages#about'
  get    '/auth/:provider/callback', to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: %i[edit destroy] do
    resources :events, only: %i[index edit update create destroy] do
      resources :histories, only: %i[index create destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, uniqueness: { scope: :provider }

  def self.find_by_auth(auth)
    return unless auth && auth.valid?

    find_by_provider_and_uid(auth['provider'], auth['uid'])
  end

  def self.create_with_auth!(auth)
    return unless auth && auth.valid?

    user ||= User.create_with_auth!(auth)
    create!(user: user, uid: auth['uid'], provider: auth['provider'])
  end
end

app/models/event.rb
class Event < ApplicationRecord
  after_create :create_first_date
  validates_presence_of :user_id, :title, :occurred_at
  validates_uniqueness_of :title, uniqueness: { scope: :user_id }
  belongs_to :user
  has_many :histories, dependent: :delete_all

  private

    def create_first_date
      histories.create(occurred_at: occurred_at)
    end

    def self.search(term)
      term ? where(['title LIKE ?', "%#{term}%"]) : all
    end
end

app/models/history.rb
class History < ApplicationRecord
  after_save :update_event_after_save
  before_destroy :update_event_before_destroy
  validates_presence_of :occurred_at
  belongs_to :event
  default_scope -> { order(occurred_at: :desc) }

  private

    def update_event_after_save
      event.update(occurred_at: event.histories.first.occurred_at)
    end

    def update_event_before_destroy
      event.update(occurred_at: event.histories.where.not(id: id).first.occurred_at)
    end
end

app/models/occurred_date.rb
class OccurredDate < ApplicationRecord
  after_save :update_event_after_save
  before_destroy :update_event_before_destroy
  belongs_to :event
  default_scope -> { order(occurred_at: :desc) }
  validates_presence_of :occurred_at

  private

    def update_event_after_save
      self.event.update(occurred_at: self.event.occurred_dates.first.occurred_at)
    end

    def update_event_before_destroy
      self.event.update(occurred_at: self.event.occurred_dates.where.not(id: self.id).first.occurred_at)
    end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_many :authorizations, dependent: :destroy
  has_many :events, dependent: :destroy

  def self.create_with_auth!(auth)
    create!(email: auth['info']['email'])
  end

  def update_email(email_from_auth)
    email.casecmp(email_from_auth) != 0 && update(email: email_from_auth)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      return if logged_in?

      store_location
      flash[:danger] = 'Please sign in.'
      redirect_to root_url
    end

    # 正しいユーザーかどうか確認
    def correct_user
      return if current_user?(@user)

      flash[:danger] = 'Wrong user.'
      redirect_to root_url
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, :set_user, :correct_user
  before_action :set_event, only: %i[destroy edit update]

  def index
    @events = @user.events.paginate(page: params[:page]).order('occurred_at DESC')
    params[:event] && @events = @events.search(params[:event][:term])
  end

  def create
    @event = @user.events.build(event_params)
    if @event.save
      flash[:success] = 'Event created!'
    else
      flash[:danger] = 'Failed to create event.'
    end
    redirect_to user_events_path(@user.id)
  end

  def destroy
    @event.destroy
    flash[:success] = 'Event deleted.'
    redirect_to user_events_path(@user.id)
  end

  def edit
    @histories = @event.histories.paginate(page: params[:page])
  end

  def update
    flash[:danger] = 'Failed to update event.' unless @event.update(event_params)
    redirect_to user_event_histories_path(@event.user.id, @event.id)
  end

  private

    def event_params
      params.require(:event).permit(:title, :occurred_at, :term)
    end

    def set_event
      @event = @user.events.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :logged_in_user, :set_user, :correct_user, :set_event
  before_action :set_history, only: [:destroy]

  def index
    @histories = @event.histories.paginate(page: params[:page])
  end

  def create
    @history = @event.histories.build(history_params)
    if @history.save
      flash[:success] = 'Event updated.'
    else
      flash[:danger] = 'Event update failed.'
    end
    redirect_to user_event_histories_path(@event.user.id, @event.id)
  end

  def destroy
    eid = @history.event_id
    if @history.event.histories.size == 1
      flash[:danger] = 'Cannot delete last one date.'
    else
      flash[:success] = 'Date deleted.'
      @history.destroy
    end
    redirect_to user_event_histories_path(@user.id, eid)
  end

  private

    def history_params
      params.require(:history).permit(:occurred_at)
    end

    def set_event
      @event = @user.events.find(params[:event_id])
    end

    def set_history
      @history = @event.histories.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    if auth.blank?
      flash.now[:danger] = 'Authorization failed.'
      return redirect_to root_url
    end

    @auth = Authorization.find_by_auth(auth)
    if @auth
      @auth.user.update_email(auth['info']['email'])
    else
      @auth = Authorization.create_with_auth!(auth)
    end
    user = @auth.user
    log_in user
    redirect_back_or user_events_path(user.id)
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to user_events_path(current_user.id) if logged_in?
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, :set_user, :correct_user

  def edit; end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'Your account is successfully deleted.'
    redirect_to root_url
  end

  private

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = 'When is the last time?'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザーがログインしていればtrue、その他ならばfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

# 記憶したURL (もしくはデフォルト値) にリダイレクト
def redirect_back_or(default)
  redirect_to(session[:forwarding_url] || default)
  session.delete(:forwarding_url)
end

# アクセスしようとしたURLを覚えておく
def store_location
  session[:forwarding_url] = request.original_url if request.get?
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<li id="event-<%= event.id %>">
  <span class="title">
    <%= link_to user_event_histories_path(event.user.id, event.id) do %>
      <span class="fa fa-calendar"> <%= event.title%></span>
    <% end %>
  </span>
  <span class="timestamp">
    <%= pluralize((Date.current - (event.occurred_at.to_date)).numerator, "day") %> ago /
    <%= pluralize(event.histories.count, "time") %>
    <% if current_user?(event.user) %>
      <%= link_to user_event_path(event.user.id, event.id), method: :delete , data: { confirm: "You sure?" } do %>
        <span class="fa fa-trash"> delete</span>
      <% end %>
    <% end %>
  </span>
</li>

app/views/events/edit.html.erb
<% provide(:title, @event.title) %>
<div class="row">
  <aside class="col-lg-4">
    <section class="user_info">
      <h5>
        <%= link_to user_events_path(@event.user.id) do %>
          <span class="fa fa-step-backward"> Back</span>
        <% end %>
      </h5>
      <h5>
        <span class="fa fa-calendar"> <%= @event.title %></span>
      </h5>
    </section>
    <section>
      <%= render "shared/edit_event_form", event: @event %>
    </section>
    <section>
      <%= render "shared/history_form", event: @event %>
    </section>
  </aside>
  <%= render "shared/histories", histories: @histories %>
</div>

app/views/events/index.html.erb
<% provide(:title, "My events") %>
<div class="row">
  <aside class="col-lg-4">
    <section>
      <h5><span class="fa fa-user"></span> <%= @user.email %></h5>
    </section>
    <section class="event_form">
      <%= render "shared/event_form", user: @user %>
    </section>
  </aside>
  <div class="col-lg-8">
    <%= render "shared/search_event_form", user: @user %>

    <% if @user.events.any? %>
      <h3><%= pluralize(@events.count, "event") %></h3>
      <ol class="events">
        <%= render @events %>
      </ol>
      <div class="d-flex flex-column align-items-center">
        <%= will_paginate @events, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= link_to current_user do %>
          <i class="glyphicon glyphicon-step-backward"></i> back
        <% end %>
      </h1>
      <h1>
        <i class="glyphicon glyphicon-tag"></i>
        <%= link_to @event.title, edit_event_path(@event.id), remote: true %>
      </h1>
    <section class="forms">
      <div id="edit_form"></div>
      <div>
        <%= render 'shared/history_form', {event: @event} %>
      </div>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @event.histories.any? %>
      <h3><%= pluralize(@event.histories.count, "date") %></h3>
      <ol class="events">
        <%= render @histories %>
      </ol>
      <%= will_paginate @histories %>
    <% end %>
  </div>
</div>

app/views/histories/_history.html.erb
<li id="history-<%= history.id %>">
  <span class="content fa fa-check"> <%= history.occurred_at.strftime("%Y/%m/%d %H:%M") %></span>
  <span class="timestamp">
    <%= pluralize((Date.current - (history.occurred_at.to_date)).numerator, "day") %> ago
    <% if current_user?(history.event.user) %>
      <%= link_to user_event_history_path(history.event.user.id, history.event.id, history.id), method: :delete, data: { confirm: "You sure?" } do %>
        <span class="fa fa-trash"> delete</span>
      <% end %>
    <% end %>
  </span>
</li>

app/views/histories/index.html.erb
<% provide(:title, @event.title) %>
<div class="row">
  <aside class="col-lg-4">
    <section>
      <h5>
        <%= link_to user_events_path(@event.user.id) do %>
          <span class="fa fa-step-backward"> Back</span>
        <% end %>
      </h5>
      <h5>
        <%= link_to edit_user_event_path(@event.user.id, @event.id) do %>
          <span class="fa fa-calendar"> <%= @event.title %></span>
        <% end %>
      </h5>
    <section class="forms">
      <%= render "shared/history_form", event: @event %>
    </section>
  </aside>
  <%= render "shared/histories", histories: @histories %>
</div>

app/views/layouts/_footer.html.erb
<footer class="border-top">
  <small>
    When is the last time?
    by tkms0106
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "When is the last time?", root_path, class: "navbar-brand", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav mr-auto">
        <li>
          <%= link_to about_path, class: "nav-link" do %>
            <span class="fa fa-info-circle"> About</span>
          <% end %>
        </li>
        <li>
          <%= link_to "https://github.com/tkms0106/last-time-webapp/blob/master/README.md", class: "nav-link" do %>
            <span class="fa fa-question-circle"> Help</span>
          <% end %>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fa fa-user-circle"> Account</span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to user_events_path(current_user.id), class: "dropdown-item" do %>
                  <span class="fa fa-calendar"> My events</span>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_path(current_user), class: "dropdown-item" do %>
                  <span class="fa fa-exclamation-triangle"> Delete account</span>
                <% end %>
              </li>
              <li class="dropdown-divider"></li>
              <li>
                <%= link_to logout_path, method: :delete, class: "dropdown-item" do %>
                  <span class="fa fa-sign-out"> Sign out</span>
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
    <%= favicon_link_tag %>
    <%= javascript_pack_tag "application" %>
    <%= stylesheet_pack_tag "application" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_datetimepicker.html.erb
<div id="popup-picker" data-type="<%= resource %>"></div>
<%= javascript_pack_tag "datetimepicker" %>

app/views/shared/_edit_event_form.html.erb
<%= form_with model: event, url: user_event_path do |f| %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.button class: "btn btn-secondary" do %>
    <span class="fa fa-pencil"> Update event</span>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_event_form.html.erb
<%= form_with model: Event.new, url: user_events_path(user.id) do |f| %>
  <%= f.text_field :title, class: "form-control", placeholder: "Event title" %>
  <%= render "shared/datetimepicker", resource: "event" %>
  <%= f.button class: "btn btn-secondary" do %>
    <span class="fa fa-pencil"> Create event</span>
  <% end %>
<% end %>

app/views/shared/_histories.html.erb
<div class="col-lg-8">
	<% if @event.histories.any? %>
		<h3><%= pluralize(@event.histories.count, "time") %></h3>
		<ol class="events">
			<%= render histories %>
		</ol>
		<div class="d-flex flex-column align-items-center">
			<%= will_paginate histories, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
		</div>
	<% end %>
</div>

app/views/shared/_history_form.html.erb
<%= form_with model: History.new, url: user_event_histories_path(event.user.id, event.id) do |f| %>
  <%= render "shared/datetimepicker", resource: "history" %>
  <%= f.button class: "btn btn-secondary" do %>
    <span class="fa fa-plus"> Add date</span>
  <% end %>
<% end %>

app/views/shared/_occurred_date_form.html.erb
<%= bootstrap_form_for OccurredDate.new do |f| %>
  <div class="field">
    <%= render 'shared/datetimepicker', {f: f} %>
  </div>
  <%= f.hidden_field :event_id, :value => event.id %>
  <%= f.submit "Add date", class: "btn btn-primary" %>
<% end %>

app/views/shared/_search_event_form.html.erb
<%= form_with scope: :event, url: user_events_path(user.id), method: :get do |f| %>
  <div class="form-group">
    <div class="input-group mb-3">
      <%= f.text_field :term, class: "form-control", "aria-describedby": "button-addon2" %>
      <div class="input-group-append">
        <%= f.button name: nil, class: "btn btn-info", id: "button-addon2" do %>
          <span class="fa fa-search"> Search</span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<div class="d-flex flex-column align-items-center">
  <div>
    <p>
      「最後に○○したのはいつだっけ？」を振り返るために作ったアプリケーションです。利用にはGoogleアカウントが必要です。<br>
      アプリケーションはGoogleアカウントからメールアドレスを取得・保存しますが、それ以外のアカウント情報は取得しません。
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron d-flex flex-column align-items-center">
  <h1>Look back <b>WHAT & WHEN</b> you did</h1>
  <% unless logged_in? %>
    <div class="row">
      <div class="col">
        <p>
          <%= link_to "/auth/google_oauth2", class: "btn btn-primary btn-social btn-google" do %>
            <span class="fa fa-google"> Sign in with Google</span>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Delete account") %>
<h1>Delete account</h1>

<div class="d-flex flex-column align-items-center">
  <div>
    アカウントを削除すると、イベントデータはすべて削除され、復元することはできません。<br>
    また、本アプリがGoogleアカウントから読み取った情報もすべて削除されます。<br>
    よろしければ、ボタンを押してください。
  </div>
  <br>
  <div>
    <%= link_to user_path, method: "delete", class: "btn btn-danger", data: { confirm: "You sure?" } do %>
      <span class="fa fa-exclamation-triangle"> Delete my account</span>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <i class="glyphicon glyphicon-user"></i>
        <%= @user.email %>
      </h1>
    </section>
    <section class="event_form">
      <%= render 'shared/event_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.events.any? %>
      <h3><%= pluralize(@user.events.count, "event") %></h3>
      <ol class="events">
        <%= render @events %>
      </ol>
      <%= will_paginate @events %>
    <% end %>
  </div>
</div>